### ISSUE TITLE
Add `double_parens`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#10]
# What it does

Checks for unnecessary double parentheses.

# Why is this bad?

This makes code harder to read and might indicate a mistake.

# Example

```rs
fn simple_double_parens() -> i32 {
   ((0))
}

foo((0));
```

Use instead:

```rs
fn simple_no_parens() -> i32 {
   0
}

foo(0);
```
https://rust-lang.github.io/rust-clippy/master/index.html#/double_parens

**Comment by coxmars** [comment]
Hi @0xLucqs can I help you with this one? 🫡

**Comment by 0xLucqs** [comment]
sure can you join the telegram group as well so i can help if you're stuck or don't know how to start ? https://t.me/cairolint

**Comment by coxmars** [comment]
> sure can you join the telegram group as well so i can help if you're stuck or don't know how to start ? https://t.me/cairolint

Sure thanks, I will work in this asap and I will let you know if I have issues 🫡
