### ISSUE TITLE
Add `duplicate_underscore_argument`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#11]
# What it does

Checks for function arguments having the similar names differing by an underscore.

# Why is this bad?

It affects code readability.

# Example

```rs
fn foo(a: i32, _a: i32) {}
```

Use instead:

```rs
fn foo(a: i32, _b: i32) {}
```
https://rust-lang.github.io/rust-clippy/master/index.html#/duplicate_underscore_argument

**Comment by stevencartavia** [comment]
Hi, can I take this?

**Comment by 0xLucqs** [comment]
sure can you join the telegram group as well so i can help if you're stuck or don't know how to start ? https://t.me/cairolint
