### ISSUE TITLE
Add `break_unit`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#13]
# What it does

Find all `break ();` usages. 

# Why restrict this

Empty brackets after `break` usage are redundant and can be omitted, and it may be desirable to do so consistently for style.

# Example

```rs
loop {
    break ();
};
```

Use instead:

```rs
loop {
    break;
};
```

**Comment by raizo07** [comment]
Hello @0xLucqs Can I work on this?

**Comment by 0xLucqs** [comment]
sure ! join the telegram group as well so it's easier for help and coordination t.me/cairolint
