### ISSUE TITLE
Add `equatable_if_let`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#16]
# What it does

Checks for pattern matchings that can be expressed using equality.

# Why is this bad?

It reads better and has less cognitive load because equality won’t cause binding.
It is a [Yoda condition](https://en.wikipedia.org/wiki/Yoda_conditions). Yoda conditions are widely criticized for increasing the cognitive load of reading the code.
Equality is a simple bool expression and can be merged with && and || and reuse if blocks

# Example

```rs
if let Option::Some(2) = x {
   do_thing();
}
```

Use instead:

```rs
if x == Option::Some(2) {
   do_thing();
}
```

**Comment by BernalHQ** [comment]
Hi @0xLucqs, can i try this?

**Comment by 0xLucqs** [comment]
sure can you join the telegram group as well so i can help if you're stuck or don't know how to start ? https://t.me/cairolint

**Comment by BernalHQ** [comment]
Thanks @0xLucqs
