### ISSUE TITLE
Add `bool_comparison`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#36]
# What it does

Checks for expressions of the form x == true, x != true and order comparisons such as x < true (or vice versa) and suggest using the variable directly.

# Why is this bad?

Unnecessary code.

# Example

```rs
if x == true {}
if y == false {}
```

use x directly:

```rs
if x {}
if !y {}
```
https://rust-lang.github.io/rust-clippy/master/index.html#/bool_comparison

**Comment by lauchaves** [comment]
Hey @0xLucqs, may I give this one a try ? 🚀
