### ISSUE TITLE
Add `collapsible_if`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#37]
# What it does

Checks for nested if statements which can be collapsed by &&-combining their conditions.

# Why is this bad?

Each if-statement adds one level of nesting, which makes code look more complex than it really is.

# Example

```rs
if x {
    if y {
        // …
    }
}
```

Use instead:

```rs
if x && y {
    // …
}
```

**Comment by jimenezz22** [comment]
gm @0xLucqs 
I could help with this issue
