### ISSUE TITLE
Make the project usable as a scarb subcommand

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#4]
Using [clap](https://docs.rs/clap/latest/clap/) write the `cairo-lint-cli` crate so it can be used as [scarb subcommand](https://docs.swmansion.com/scarb/docs/writing-extensions/subcommands.html). It should fetch the path to the corelib using [scarb metadata](https://docs.rs/scarb-metadata/latest/scarb_metadata/index.html) and should process the command arguments using [scarb ui](https://docs.rs/scarb-ui/latest/scarb_ui/args/struct.PackagesFilter.html).
[Here](https://github.com/software-mansion/scarb/blob/7d24c76673e9e91d168208718e86c1143bdd947e/extensions/scarb-cairo-run/src/main.rs#L74) is an example of such an integration
Currently the capabilities should be:
* `cairo-lint check` (this would check the whole workspace and print the diagnostics)
* `cairo-lint fix` (fix all the diagnostics reported by cairo-lint in place)
Feel free to suggest other commands as well

**Comment by coxmars** [comment]
Hi @0xLucqs, I've been really enjoying contributing to this project and would love to take on this issue. Could you please assign it to me? 🫡

**Comment by 0xLucqs** [comment]
yes done
