### ISSUE TITLE
Pretty print diagnostics

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#5]
Use [this crate](https://docs.rs/annotate-snippets/latest/annotate_snippets/) to prettily format diagnostics while it's not integrated yet in the compiler

**Comment by Xavek** [comment]
@0xLucqs  I want to try this

**Comment by 0xLucqs** [comment]
Hey @Xavek any news ?

**Comment by Xavek** [comment]
@0xLucqs I have unassigned myself. I caught up with other things and it looks like I would be occupied. Couldn't finish, next time

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-lint).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!
I have over 5 years of experience with JavaScript, React, TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica.
Feel free to check out my OnlyDust profile and my GitHub profile: lauchaves!


### How I plan on tackling this issue
I'd follow this approach: 

- I'll add the new dependency `annotate-snippets`
- Import and use the crate in the code 
- I'll create and format diagnostics would make a function called `format_diagnostic` for it 
- I’d find where diagnostics are currently output and replace that code with a call to `format_diagnostic`
- I’d  run the linter to ensure diagnostics are ok and the output is correctly formatted as well

**Comment by 0xLucqs** [comment]
sounds good let's go
