### ISSUE TITLE
Add `manual_unwrap_or_default`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#67]
# What it does

Checks if a match or if let expression can be simplified using .unwrap_or_default().

# Why is this bad?

It can be done in one call with .unwrap_or_default().

# Example

```cairo
let x: Option<Array<u32>> = Some(array![]);
let y: Array<u32> = match x {
    Some(v) => v,
    None => Default::default(),
};

let x: Option<Array<u32>> = Some(ArrayTrait::new());
let y: Vec<Array<u32>> = if let Some(v) = x {
    v
} else {
    Default::default()
};
```

Use instead:

```cairo
let x: Option<Array<u32>> = Some(array![]);
let y: Array<u32> = x.unwrap_or_default();

let x: Option<Array<u32>> = Some(ArrayTrait::new());
let y: Array<u32> = x.unwrap_or_default();
```

(the examples are for arrays but it can work with any type that implements default

**Comment by JoE11-y** [comment]
Hi @0xLucqs can I help out with this?

**Comment by 0xLucqs** [comment]
@JoE11-y sure, do you have any idea on how to solve this ?

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-lint).

### My background and how it can be leveraged
Hello, I available to work on this task. I will be glad if this task is assigned to me

**Comment by JoE11-y** [comment]
> @JoE11-y sure, do you have any idea on how to solve this ?

Yes I can. Will take reference from here.

https://rust-lang.github.io/rust-clippy/master/index.html#/manual_unwrap_or_default

Plus I have extensive XP working with Cairo.

**Comment by chachaleo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cairo-lint).

### My background and how it can be leveraged
I have contributed to a lot of projects in Starknet, I have experience in Rust


### How I plan on tackling this issue
Read the code base and merged PR and implement in a similar way

**Comment by 0xLucqs** [comment]
okay @JoE11-y i'll assign the issue to you

**Comment by 0xLucqs** [comment]
@chachaleo @lindsaymoralesb @Benjtalkshow i'll create other issues for you
