### ISSUE TITLE
Add `manual_ok_or`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#72]
# What it does

Finds patterns that reimplement Option::ok_or.

# Why is this bad?

Concise code helps focusing on behavior instead of boilerplate.

# Examples

```cairo
let foo: Option<i32> = None;
let foo = match foo {
    Option::Some(v) => Result::Ok(v),
    Option::None => Result::Err('this is an err'),
}
```

Use instead:

```cairo
let foo: Option<i32> = None;
foo.ok_or('this is an err');
```

**Comment by 0xLucqs** [comment]
@chachaleo you can do that one

**Comment by chachaleo** [comment]
Ok I'll get started thanks :)

**Comment by 0xLucqs** [comment]
you can ping me on tg (xLucqs) if you need help and this is the group of the project https://t.me/cairolint
