### ISSUE TITLE
Add `int_plus_one`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#79]
# What it does

Checks for usage of `x >= y + 1` or `x - 1 >= y` (and `<=`) in a block

# Why is this bad?

Readability – better to use `> y` instead of `>= y + 1`.

# Example

```cairo
if x >= y + 1 {}
```

Use instead:

```cairo
if x > y {}
```

**Comment by sebas11042** [comment]
Hi! @0xLucqs 

I’ve been reviewing the "Add int_plus_one" issue and see that the main problem is improving code readability by removing expressions like x >= y + 1 or x - 1 >= y, which complicate things a bit. Replacing them with something simpler like x > y would make the code easier to understand.

I’m an advanced computer science student with knowledge in Java and JavaScript, and a member of the DOJO Coding community here in CR. I plan to propose changes based on this idea, ensuring that the code remains functional while improving its readability.

Thanks!

**Comment by 0xLucqs** [comment]
Let’s go!

**Comment by sebas11042** [comment]
Great @0xLucqs I'm excited to get started!

**Comment by 0xLucqs** [comment]
hello any news ?

**Comment by Manush-2005** [comment]
Hey @0xLucqs , I would like to take this issue up if there is any inactivity

**Comment by 0xLucqs** [comment]
sorry this project is finished
