### ISSUE TITLE
Add `ifs_same_cond`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#87]
# What it does

Checks for consecutive ifs with the same condition.

# Why is this bad?

This is probably a copy & paste error.

# Example

```cairo
if a == b {
    …
} else if a == b {
    …
}
```
Note that this lint ignores all conditions with a function call as it could have side effects:

```cairo
if foo() {
    …
} else if foo() { // not linted
    …
}
```

**Comment by Gianfranco99** [comment]
Hello, I want to work on this!
