### ISSUE TITLE
Add `double_comparison`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/cairo-lint#9]
# What it does

Checks for double comparisons that could be simplified to a single expression.

# Why is this bad?

Readability.

# Example

```rs
if x == y || x < y {}
```
Use instead:
```rs
if x <= y {}
```
https://rust-lang.github.io/rust-clippy/master/index.html#/double_comparisons

**Comment by renzobanegass** [comment]
Hi, can I take this one?

**Comment by 0xLucqs** [comment]
Yes please do @renzobanegass
